### ISSUE TITLE
Small thing: Link to PowerShell script wrong

### ISSUE THREAD

**Issue by MystiChronos** [eneerge/CIS-Microsoft-Intune-For-Windows-IntuneProfile#7]
Dear eneerge,

In this part, there is a wrong link:

> To import a profile:
> Download this Powershell Script: [IntuneConfiguration_ImportCustomConfig.ps1](https://github.com/eneerge/CIS-Microsoft-Intune-For-Windows-IntuneProfile/blob/main/ImportScript/IntuneConfiguration_ImportCustomConfig.ps1)

Either link should be:
https://github.com/eneerge/CIS-Microsoft-Intune-For-Windows-IntuneProfile/blob/main/Windows%2010/ImportScript/ImportScriptIntuneConfiguration_ImportCustomConfig.ps1

Or the ImportScript folder needs to be moved to root.

**Comment by eneerge** [comment]
Thanks. I moved the Import Script into the Windows 10 folder, because the Windows 11 no longer uses it. I've updated the link.
